### PR TITLE
Add bootstrap tooltips to ability links

### PR DESCRIPTION
**Pull request by Shourn**
I thought being able to reference a linked ability at a glance would be useful.
Since I couldn't find a contribution guide I hope this PR is nonetheless of sufficient quality.

### CODE REVIEW

**Comment by callmepartario** [comment]
this is great, thank you so much! i will implement this today, but need to make a few changes to filenames, js, and styling, so i will do that manually instead of a merge.

**Comment by Shourn** [comment]
That's great to hear. Thank you for your hard work and the absolutely amazing resource you provide.

**Comment by callmepartario** [comment]
i've got these mostly working. i can't seem to figure out how to add a second class to the js snipped -- is there a clear way to add to the div that gets created that it's a .tooltip but also add the .theme-light class? that'd let us style them differently for dark and light mode versions of the page.

fyi, i'm adding you to the acknowledgements section of the page once a i get a moment.

**Comment by callmepartario** [comment]
gotcha, i see how that selection process works. i really should have thought of trying that, in retrospect. thanks again!

**Pull request closed without merging**
